POST http://localhost:3000/detailed
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiV2luZG93cyIsImlhdCI6MTYwNDMxMTgzNX0.nomIr_sa8BxkZVpWWfeQ4dT5ciXeyc-TbdhjEqtWj-w
Content-Type: application/json

{
  "id" : "1"
}
###

POST http://localhost:4000/renew_token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiV2luZG93cyIsImlhdCI6MTYwNDMxMTgzNX0.nomIr_sa8BxkZVpWWfeQ4dT5ciXeyc-TbdhjEqtWj-w"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
  "platform": "Windows"
}

###

POST http://localhost:3000/create_article
Content-Type: application/json

{
  "title": "This title",
  "imageUrl": "somekindofurl",
  "description": "this could be a very long description of the article but I don't want this to be very long, I think this might be just it tho."
}

###

GET http://localhost:3000/list/2/4
